#!/bin/bash
clear
echo -e "\n\tWelcome GPG-FIX !\n
             |-------------------------------------------|
             |                                           |
             |        Fix GPG Manjaro -> (  1  )         |
             |        Fix GPG Archlinux -> (  2  )       |
             |        Fix GPG BlackArch -> (  3  )       |
             |     Fix GPG BlackArch + Manjaro  (  4  )  |
             |    Fix GPG BlackArch + Archlinux  (  5  ) |
             |                                           |
             |-------------------------------------------|\n

\n\tEnter: " 

read main_menu

case "$main_menu" in
   "1")
      sudo pacman-mirrors --fasttrack
      sudo pacman -Sy gnupg archlinux-keyring manjaro-keyring --noconfirm
      sudo rm -r /etc/pacman.d/gnupg
      sudo pacman-key --init
      sudo pacman-key --populate archlinux manjaro
      sudo pacman-key --refresh-keys
      sudo pacman -Sy gnupg archlinux-keyring manjaro-keyring --noconfirm
      ;;
   "2")
      sudo pacman -Sy gnupg archlinux-keyring --noconfirm
      sudo rm -r /etc/pacman.d/gnupg
      sudo pacman-key --init
      sudo pacman-key --populate archlinux
      sudo pacman-key --refresh-keys
      sudo pacman -Sy gnupg archlinux-keyring --noconfirm
      ;;
   "3")
      sudo pacman -Sy gnupg archlinux-keyring blackarch-keyring --noconfirm
      sudo rm -r /etc/pacman.d/gnupg
      sudo pacman-key --init
      sudo pacman-key --populate archlinux blackarch
      sudo pacman-key --refresh-keys
      sudo pacman -Sy gnupg archlinux-keyring blackarch-keyring --noconfirm
      ;;
   "4")
      sudo pacman-mirrors --fasttrack 
      sudo pacman -Sy gnupg archlinux-keyring manjaro-keyring blackarch-keyring --noconfirm
      sudo rm -r /etc/pacman.d/gnupg
      sudo pacman-key --init
      sudo pacman-key --populate archlinux manjaro blackarch
      sudo pacman-key --refresh-keys
      sudo pacman -Sy gnupg archlinux-keyring manjaro-keyring blackarch-keyring --noconfirm
      ;;
   "5")
      sudo pacman -Sy gnupg archlinux-keyring blackarch-keyring --noconfirm
      sudo rm -r /etc/pacman.d/gnupg
      sudo pacman-key --init
      sudo pacman-key --populate archlinux blackarch
      sudo pacman-key --refresh-keys
      sudo pacman -Sy gnupg archlinux-keyring blackarch-keyring --noconfirm
      ;;
esac

echo -e "\n\tDone !  :)\n"
